instrumentation:
  root: '.'
  default-excludes: true
  excludes:
    - 'src/style/**'
    - 'webpack/**'
    - 'lib/**'
    - 'index.js'
  embed-source: false
  complete-copy: false
  include-all-sources: true
reporting:
  print: summary
  reports:
    - lcov
    - cobertura
  dir: ./coverage
  watermarks:
    statements: [99, 100]
    lines: [99, 100]
    functions: [99, 100]
    branches: [99, 100]